services:
  - type: web
    name: chatconnect-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://himanshu:Himanshu06@cluster0.gjqrhqb.mongodb.net/chatconnect?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: chatconnect_super_secret_jwt_key_2025_internship_demo
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: chatconnect-frontend
    env: static
    rootDir: mobile
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
