[build]
  command = "npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  API_BASE_URL = "https://chatconnect-backend-u3di.onrender.com/api"
  SOCKET_URL = "https://chatconnect-backend-u3di.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
